#!/bin/bash
#program
#  user input his first name and lastname and then we echo to them
#History
#2015/Dec 6 zhouhao2 first release

read -p "please input your first name :" firstname 
read -p "please input your last name  :" lastname
echo -e "\n your full name is $firstname $lastname" 

