#!/bin/bash
#program
#    use to : premitive sh_015 by function
#History
#2015/Dec 10 zhouhao2 first release

function printit (){
   
    echo -e "\$0 is $0"
    echo -e "\$1 is $1"
    echo your choice is $1

}

read -p "please give me your choice from(1,2,3):" number

case "$number" in
     "1")
      printit 1
     ;;
     "2")
      printit 2
     ;;
     "3")
      printit 3
     ;;
      *)
      echo "don't kid me!!"
     ;;
esac
 



