#!/bin/sh

count=20000
i=1
while(($i<$count))
do
echo "into livetv"
date +%s_%N

#into livetv
input keyevent 170 

#sleep 2 second
sleep 4

echo "into huhaokan"
date +%s.%N

#into media 
input keyevent 209

#sleep 2 second
sleep 4

i=$(($i+1))
done
