#!/bin/sh
for i in A B C D; do 
{
echo $i && sleep 3
}
done

#do each in bg parallel
for i in {1..3}; do 
{
echo $i && sleep 3
}&
done

#use seq for
pkgs=( $(pm list packages) );for i in $(busybox seq ${#pkgs[@]} );do dumpsys package ${pkgs[$i]}; done;
